version: '2'

services:
  web:
    image: ligero/ligerosmart:6.1-nginx
    volumes:
      - ligerosmart-data:/opt/otrs
      - ./app-backups:/app-backups
    restart: always
    environment:
      APP_FQDN: localhost.localdomain
      APP_DatabaseType: postgresql
      APP_DatabaseHost: database
      APP_Database: ligerosmart
      APP_DatabaseUser: postgres
      APP_DatabasePw: postgres
      APP_NodeID: 1
      APP_LigeroSmart_Node: elasticsearch
      APP_CustomerID: ligerosmart
      APP_DefaultLanguage: pt_BR
      TZ: America/Sao_Paulo
      #START_WEBSERVER: 1
      #START_SCHEDULER: 1
      #START_SSHD: 0
      #SSH_PASSWORD: 
      #DEBUG_MODE: 0
      #ROOT_PASSWORD: ligero
    ports:
      - "8008:80"
      #- "2202:22"

  database:
    image: postgres:9.5
    volumes:
      - postgres-data:/var/lib/postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ligerosmart
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  elasticsearch:
    image: ligero/elasticsearch:6.5.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=otrs-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  grafana:
    image: ligero/grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
        
volumes:
  ligerosmart-data:
    driver: local
  postgres-data:
    driver: local
  elasticsearch-data:
    driver: local
  grafana-data:
    driver: local

