version: '2.4'

services:

  ingress:
    image: traefik:v1.7
    restart: always
    command: 
      # - --api
      - --docker
      - --docker.watch=true 
      - --docker.exposedbydefault=false
      - --debug=false
      - --logLevel=WARN
      ## HTTP only (remove line above if HTTPS is active)
      - --entryPoints=Name:http Address::80
      ## HTTPS
      #- --defaultentrypoints=https,http
      #- --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      #- --entryPoints=Name:https Address::443 TLS
      ## letsencrypt
      #- --acme
      #- --acme.email=${ACME_EMAIL}
      #- --acme.storage=/ssl/acme.json
      #- --acme.entryPoint=https
      #- --acme.onHostRule=true
      #- --acme.httpchallenge.entrypoint=http
      # other ssl
      #- --entryPoints=Name:https Address::443 TLS:/ssl/www.mycert.com.crt,/ssl/www.mycert.com.key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ssl:/ssl/
    ports:
      - 80:80
      - 443:443 

  web:
    image: ligero/ligerosmart:6.1-nginx
    volumes:
      - ligerosmart-core:/opt/otrs
      - ligerosmart-custom:/opt/otrs/Custom
      - ligerosmart-article:/opt/otrs/var/article
      - ./app-backups:/app-backups
    restart: always
    environment:
      APP_FQDN: ${WEBSERVER_FQDN:-localhost.localdomain}
      APP_DatabaseType: mysql
      APP_DatabaseHost: database
      APP_Database: ligerosmart
      APP_DatabaseUser: ligerosmart
      APP_DatabasePw: ligerosmart
      APP_NodeID: 1
      APP_LigeroSmart_Node: elasticsearch
      APP_CustomerID: ligerosmart
      APP_DefaultLanguage: pt_BR
      TZ: America/Sao_Paulo
      START_WEBSERVER: 1
      START_SCHEDULER: 1
      #START_SSHD: 0
      #SSH_PASSWORD: 
      #DEBUG_MODE: 0
      #ROOT_PASSWORD: ligero
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.default-path.frontend.rule=PathPrefix:/
      - traefik.otrs-path.frontend.rule=PathPrefix:/otrs
      - traefik.user-path.frontend.rule=Path:/atendente;ReplacePath:/otrs/index.pl
      # set root path to customer 
      #- traefik.customer-path.frontend.rule=Path:/;ReplacePath:/otrs/customer.pl
      - traefik.protocol=http
      
  # Redis cache
  # Configuration reference on https://docs.ligerosmart.com
  #cache:
  #  image: redis:6-buster
  #  restart: always
    
  database:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ligerosmart
      MYSQL_DATABASE: ligerosmart
      MYSQL_USER: ligerosmart
      MYSQL_PASSWORD: ligerosmart
    command:
      - --max-allowed-packet=64M
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=256M
      - --character-set-server=utf8
      - --bind-address=0.0.0.0

  elasticsearch:
    image: ligero/elasticsearch:6.5.1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=ligerosmart-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    labels:
      - traefik.enable=true
      - traefik.port=9200
      - traefik.es-path.frontend.rule=PathPrefixStrip:/elasticsearch
      - traefik.es-path.frontend.auth.basic.users=admin:$$apr1$$af4muqpv$$02aLvgQLPrZxo41BqKD6H1
      - traefik.protocol=http

  grafana:
    image: ligero/grafana
    restart: always
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=/grafana/
      - GF_AUTH_BASIC_ENABLED=false # avoid elasticsearch auth
    labels:
      - traefik.enable=true
      - traefik.port=3000
      - traefik.grafana-path.frontend.rule=PathPrefixStrip:/grafana
      - traefik.protocol=http
        
volumes:
  ligerosmart-core:
    driver: local
  ligerosmart-custom:
    driver: local
  ligerosmart-article:
    driver: local
  mysql-data:
    driver: local
  elasticsearch-data:
    driver: local
  grafana-data:
    driver: local
  ssl:
    driver: local

